spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/school_management-db?createDatabaseIdNotExist=true
    username: root
    password: password
